name: Check links

on:
  schedule:
    - cron: "0 6 * * *"
  push:
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install linkchecker
        run: sudo pip install LinkChecker

      - name: Run linkchecker
        run: linkchecker https://linuxcontainers.org/ -f .linkcheckerrc

      - name: Print log
        if: failure()
        run: cat linkchecker-out.txt